-- Criação do banco
CREATE DATABASE IF NOT EXISTS `kamishibai-senai` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `kamishibai-senai`;

-- Tabela 104a
CREATE TABLE IF NOT EXISTS `104a` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nome` VARCHAR(100) NOT NULL,
    `data` DATETIME NOT NULL,
    `porta` ENUM('sim', 'nao') NOT NULL,
    `piso` ENUM('sim', 'nao') NOT NULL,
    `carteira_1` ENUM('sim', 'nao') NOT NULL,
    `carteira_2` ENUM('sim', 'nao') NOT NULL,
    `carteira_3` ENUM('sim', 'nao') NOT NULL,
    `carteira_4` ENUM('sim', 'nao') NOT NULL,
    `carteira_5` ENUM('sim', 'nao') NOT NULL,
    `carteira_6` ENUM('sim', 'nao') NOT NULL,
    `carteira_7` ENUM('sim', 'nao') NOT NULL,
    `carteira_8` ENUM('sim', 'nao') NOT NULL,
    `carteira_9` ENUM('sim', 'nao') NOT NULL,
    `carteira_10` ENUM('sim', 'nao') NOT NULL,
    `carteira_11` ENUM('sim', 'nao') NOT NULL,
    `carteira_12` ENUM('sim', 'nao') NOT NULL,
    `carteira_13` ENUM('sim', 'nao') NOT NULL,
    `carteira_14` ENUM('sim', 'nao') NOT NULL,
    `carteira_15` ENUM('sim', 'nao') NOT NULL,
    `carteira_16` ENUM('sim', 'nao') NOT NULL,
    `carteira_17` ENUM('sim', 'nao') NOT NULL,
    `carteira_18` ENUM('sim', 'nao') NOT NULL,
    `carteira_19` ENUM('sim', 'nao') NOT NULL,
    `carteira_20` ENUM('sim', 'nao') NOT NULL,
    `carteira_21` ENUM('sim', 'nao') NOT NULL,
    `carteira_22` ENUM('sim', 'nao') NOT NULL,
    `carteira_23` ENUM('sim', 'nao') NOT NULL,
    `carteira_24` ENUM('sim', 'nao') NOT NULL,
    `carteira_25` ENUM('sim', 'nao') NOT NULL,
    `carteira_26` ENUM('sim', 'nao') NOT NULL,
    `carteira_27` ENUM('sim', 'nao') NOT NULL,
    `carteira_28` ENUM('sim', 'nao') NOT NULL,
    `carteira_29` ENUM('sim', 'nao') NOT NULL,
    `carteira_30` ENUM('sim', 'nao') NOT NULL,
    `carteira_31` ENUM('sim', 'nao') NOT NULL,
    `carteira_32` ENUM('sim', 'nao') NOT NULL,
    `carteira_33` ENUM('sim', 'nao') NOT NULL,
    `carteira_34` ENUM('sim', 'nao') NOT NULL,
    `carteira_35` ENUM('sim', 'nao') NOT NULL,
    `carteira_36` ENUM('sim', 'nao') NOT NULL,
    `carteira_37` ENUM('sim', 'nao') NOT NULL,
    `carteira_38` ENUM('sim', 'nao') NOT NULL,
    `carteira_39` ENUM('sim', 'nao') NOT NULL,
    `carteira_40` ENUM('sim', 'nao') NOT NULL,
    `janela` ENUM('sim', 'nao') NOT NULL,
    `mesa_professor` ENUM('sim', 'nao') NOT NULL,
    `cadeira_professor` ENUM('sim', 'nao') NOT NULL,
    `ar_condicionado` ENUM('sim', 'nao') NOT NULL,
    `televisao` ENUM('sim', 'nao') NOT NULL,
    `quadro` ENUM('sim', 'nao') NOT NULL,
    `observacoes` TEXT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;