on:
  push:
    branches:
      - release
name: Deploy Release on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy via SFTP with password
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          REMOTE_HOST: 82.25.72.215
          REMOTE_USER: ${{ secrets.USER }}
          REMOTE_PORT: 22
          PASSWORD: ${{ secrets.PASSWORD }}
          TARGET: /public_html/kamishibai/
          SOURCE: "./"
          ARGS: -avzr --delete
          EXCLUDE: |
            .git*
            .vscode/
            _documents/
            _phpinfo.php
            *.code-workspace
            *.bkp
            *.zip
            _test.html
            _data/database/release.ini
            mergeRelease.cmd
            .env
            .github/